/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_stream_bq

import com.google.cloud.bigquery.storage.v1.BigQueryWriteClient
import com.google.cloud.bigquery.storage.v1.CreateWriteStreamRequest
import com.google.cloud.bigquery.storage.v1.JsonStreamWriter
import com.google.cloud.bigquery.storage.v1.WriteStream
import kotlinx.coroutines.*
import org.json.JSONArray
import org.json.JSONObject
import java.util.*
import java.util.concurrent.TimeUnit
import kotlin.system.measureTimeMillis

private const val ROW_NUM = 8

fun main(){

    val bqWriterV2: BQWriterV2 = BQWriterV2()

    val listOfJsonArrays = listOf(AppValues.getJsonData(ROW_NUM),AppValues.getJsonData(ROW_NUM))

    /**
     * Secuential execution
     */
    val timeExecutionWithTwoJsonStreamsSeq = measureTimeMillis{
        bqWriterV2.executeBQStreamWithTwoJsonArraysSequentially(listOfJsonArrays)
    }

    println("Time Execution With Two Json Arrays Secuentially: ".plus(timeExecutionWithTwoJsonStreamsSeq)
        .plus(" milliseconds. Seconds:").plus(timeExecutionWithTwoJsonStreamsSeq/1000))

    /**
     * Paralell execution
     */

    val timeExecuteBQStreamWithParallelStream = measureTimeMillis{
        bqWriterV2.executeBQStreamWithParallelStream(listOfJsonArrays)
    }

    println("Time Execution With Two Json Parallell Stream: ".plus(timeExecuteBQStreamWithParallelStream)
        .plus(" milliseconds. Seconds:").plus(timeExecuteBQStreamWithParallelStream/1000))

}




